---
- name: Install crictl on Kubernetes nodes
  hosts: k8s
  roles:
    - gillwong.homelab.crictl
  vars:
    crictl_download_dir: "{{ download_dir }}"
    crictl_version: "{{ k8s_crictl_version }}"
