---
- name: Apply base system configuration to all Kubernetes nodes
  hosts: k8s
  roles:
    - gillwong.homelab.k8s_base

- name: Download Kubernetes-related files
  ansible.builtin.import_playbook: k8s_download.yaml

- name: Install a container runtime on all Kubernetes nodes
  ansible.builtin.import_playbook: containerd.yaml

- name: Install and configure NVIDIA GPU for Kubernetes
  hosts: nvidia
  roles:
    - gillwong.homelab.nvidia_containerd

- name: Install crictl on all Kubernetes nodes
  ansible.builtin.import_playbook: crictl.yaml
