---
- name: Create VMs on gmsi host
  hosts: gmsi
  roles:
    - role: gillwong.homelab.create_almalinux_vm
      vars:
        create_almalinux_vm_name: k8s-cp-1
        create_almalinux_vm_ipv4s:
          - 192.168.0.131/24
        create_almalinux_vm_mem_mib: 8192
        create_almalinux_vm_vcpus: 4
        create_almalinux_vm_vol_cap_g: 128
    - role: gillwong.homelab.create_almalinux_vm
      vars:
        create_almalinux_vm_name: k8s-worker-1
        create_almalinux_vm_ipv4s:
          - 192.168.0.134/24
        create_almalinux_vm_mem_mib: 12288
        create_almalinux_vm_vcpus: 4
        create_almalinux_vm_vol_cap_g: 256
    - role: gillwong.homelab.create_almalinux_vm
      vars:
        create_almalinux_vm_name: k8s-worker-2
        create_almalinux_vm_ipv4s:
          - 192.168.0.135/24
        create_almalinux_vm_mem_mib: 12288
        create_almalinux_vm_vcpus: 4
        create_almalinux_vm_vol_cap_g: 256
  vars:
    create_almalinux_vm_pubkeys: "{{ vm_pubkeys }}"
    create_almalinux_vm_pool: lvmpool
    create_almalinux_vm_bridge: bridge0

- name: Create VMs on geqr5 host
  hosts: geqr5
  roles:
    - role: gillwong.homelab.create_almalinux_vm
      vars:
        create_almalinux_vm_name: k8s-cp-2
        create_almalinux_vm_ipv4s:
          - 192.168.0.132/24
        create_almalinux_vm_mem_mib: 6144
        create_almalinux_vm_vcpus: 4
        create_almalinux_vm_vol_cap_g: 128
    - role: gillwong.homelab.create_almalinux_vm
      vars:
        create_almalinux_vm_name: k8s-cp-3
        create_almalinux_vm_ipv4s:
          - 192.168.0.133/24
        create_almalinux_vm_mem_mib: 6144
        create_almalinux_vm_vcpus: 4
        create_almalinux_vm_vol_cap_g: 128
    - role: gillwong.homelab.create_almalinux_vm
      vars:
        create_almalinux_vm_name: k8s-worker-3
        create_almalinux_vm_ipv4s:
          - 192.168.0.136/24
        create_almalinux_vm_mem_mib: 10240
        create_almalinux_vm_vcpus: 4
        create_almalinux_vm_vol_cap_g: 256
    - role: gillwong.homelab.create_almalinux_vm
      vars:
        create_almalinux_vm_name: k8s-worker-4
        create_almalinux_vm_ipv4s:
          - 192.168.0.137/24
        create_almalinux_vm_mem_mib: 10240
        create_almalinux_vm_vcpus: 4
        create_almalinux_vm_vol_cap_g: 256
  vars:
    create_almalinux_vm_pubkeys: "{{ vm_pubkeys }}"
    create_almalinux_vm_pool: lvmpool
    create_almalinux_vm_bridge: bridge0
