---
- name: Configure Proxmox Virtual Environment nodes
  hosts: rhel
  roles:
    - gillwong.homelab.ntp

- name: Install packages
  hosts: rhel
  handlers:
    - name: Reboot system
      become: true
      ansible.builtin.reboot:

  tasks:
    - name: Install virtualization packages
      become: true
      ansible.builtin.dnf:
        name: "@Virtualization Host"
        state: present
      notify: Reboot system

    - name: Install cockpit-machines
      become: true
      ansible.builtin.dnf:
        name: cockpit-machines
        state: present

- name: Setup VM hosts
  hosts: rhel
  roles:
    - role: gillwong.homelab.libvirt_base
      vars:
        libvirt_base_pool_name: lvmpool0
        libvirt_base_vg_name: "{{ default_vg_name }}"
    - role: gillwong.homelab.libvirt_base
      vars:
        libvirt_base_pool_name: lvmpool1
        libvirt_base_vg_name: "{{ second_vg_name }}"
    - role: gillwong.homelab.update_libosinfo
      vars:
        update_libosinfo_version: "20250606"
