---
k8s:
  children:
    k8s_control_plane:
    k8s_worker:

k8s_control_plane:
  hosts:
    k8s-cp-1:
      ansible_host: 192.168.0.131
    k8s-cp-2:
      ansible_host: 192.168.0.132
    k8s-cp-3:
      ansible_host: 192.168.0.133

k8s_worker:
  hosts:
    k8s-worker-1:
      ansible_host: 192.168.0.134
    k8s-worker-2:
      ansible_host: 192.168.0.135
    k8s-worker-3:
      ansible_host: 192.168.0.136

nvidia:
  hosts:
    k8s-worker-1:
      ansible_host: 192.168.0.134
